default_platform(:mac)

platform :mac do
  desc "Deploys to AppStore Connect"
  lane :deploy do
    ensure_git_status_clean
    build_mac_app(
      scheme: "ClipNinja",
      configuration: "Release",
      clean: true,
      export_options: {
        provisioningProfiles: {
            "ninja.clip.app" => "ClipNinja AppStore"
        }
      }
    )
    upload_to_testflight
  end
end
