name: Actions

on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: xcodebuild test  -project ClipNinja.xcodeproj -scheme ClipNinja
